/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("odm-mongodb")
}

dependencies {
    // Projects
    implementation(project(":odm-core"))
    //MongoDB
    api("org.mongodb:mongodb-driver-sync:4.4.0")
    // Test
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.5.21")
}