/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("odm-core")
}

dependencies {
    // Test
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.5.21")
}