/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.oasis.okt.odm.mongodb

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class CommonTest {
    @Test fun testAdd() {
        val list = LinkedList()

        list.add("one")
        assertEquals(1, list.size())
        assertEquals("one", list.get(0))

        list.add("two")
        assertEquals(2, list.size())
        assertEquals("two", list.get(1))
    }
}
