/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val aliyunUsername: String by project
val aliyunPassword: String by project

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
    `java-library`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
}


group = "com.oasis.okt"
version = "0.0.1"

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("webLib") {
            from(components["java"])
        }
    }

    repositories {
        maven {
            // change URLs to point to your repos, e.g. http://my.org/repo
            credentials {
                username = aliyunUsername
                password = aliyunPassword
            }
            url = uri("https://packages.aliyun.com/maven/repository/2132034-release-rf0Mpj/")
        }
    }

}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}