/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.oasis.okt.odm

import org.junit.jupiter.api.Assertions
import kotlin.test.Test

class CoreTest {

    @Test
    fun testAdd() {
        val list = mutableListOf<String>()

        list.add("one")
        Assertions.assertEquals(1, list.size)
        Assertions.assertEquals("one", list[0])

        list.add("two")
        Assertions.assertEquals(2, list.size)
        Assertions.assertEquals("two", list[1])
    }
}
