/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.oasis.okt.odm.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class CoreTest {
    @Test fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }
}
